### PR TITLE
Raymarching template to be consistent with other templates

### PR DESCRIPTION
**Pull request by helgrima**

### CODE REVIEW

**Comment by einarf** [comment]
I can't see that any lines of code actually changed here from what is in master.

did you sync your local master and crate a new branch before doing these changes?

**Comment by einarf** [comment]
My guess is that we made the exact same changes to the file. I've been going through the code base removing as many references to pyopengl as possible including all examples and templates.

**Comment by helgrima** [comment]
I was almost sure that I messed up something. I will be more careful next time.

**Comment by einarf** [comment]
No worries. Hard to mess up in PRs here on github. The system is pretty good at understanding what commits to weed out. Worst case I can just squash it all into one commit. Again, if you want to make it clean, just make a PR with a branch from master. These branches you never merge, but wait until they are merged here so you can sync your master branch. Just delete the branch when the PR is merged.

Going to close this one for now as there are no actual code changes.

PS: Added you do contributors list.

**Pull request closed without merging**
