### PR TITLE
Simple raymarcher

### LINKED ISSUE #6: Default effect for raymarching
Current default effect is great for showing basic stuff, but default effect for raymarching would be great. Something like [GLSL Sandbox](http://glslsandbox.com/).

I am willing to create that effect and do pull request.

### PR DESCRIPTION
**Pull request by helgrima**
This is by no means complete raymarcher, for example light is not working as expected. But I think this should work as base for future work. Fixes #6

### CODE REVIEW

**Comment by helgrima** [comment]
Did I mess something here? As first three commits are not needed, only last three contains new code.

**Comment by einarf** [comment]
Awesome. I will look at it asap once I've pushed some changes to ModernGL. There's been a complete rewrite in the last couple of weeks and I'm ironing out some small issues here and there.

**Comment by einarf** [comment]
Had to squash the PR

**Comment by einarf** [comment]
Had to upgrade the effect to demosys 1.0. I need to update the docs asap as a lot of things have changed. The current version in `master` is also broken until ModernGL releases a new version with my PRs.

Thanks again for the contribution!

**Pull request merged**
